<a href="https://colab.research.google.com/github/yakshithnaidu-ds/Synthetic-Bank-statement-Generator/blob/main/pincode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Extract loactions and pincodes from [India Pincode Directory](https://www.data.gov.in/resource/all-india-pincode-directory-till-last-month)

Extracted IFSC codes from [Razor_IFSC](https://github.com/razorpay/ifsc?tab=readme-ov-file)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Narrations

In [3]:
import pandas as pd
df_full = pd.read_excel('/content/drive/MyDrive/Sample Data.xlsx')
display(df_full.head())
print(df_full.info())

,Transaction date,narration,transaction_type,amount,Category
0,2023-08-01,by clg 460187 052 bangalore,CREDIT,10000.0,credit reversal
1,2023-08-01,by clg 970506 002 bangalore,CREDIT,25000.0,cheque inward
2,2023-08-01,by clg 797429 015 bangalore,CREDIT,22264.0,cheque inward
3,2023-08-03,brn-clg-chq paid to branch parking /state bank of,DEBIT,5000.0,cheque outward
4,2023-08-03,ach-dr-tp ach magmafin-1211189123-utib00000000151,DEBIT,106562.0,loan/emi payment

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20165 entries, 0 to 20164
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction date  20165 non-null  datetime64[ns]
 1   narration         20165 non-null  object
 2   transaction_type  20165 non-null  object
 3   amount            20165 non-null  float64
 4   Category          20165 non-null  object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 787.8+ KB
None

In [4]:
df_full = df_full.drop(df_full.index[-1])
display(df_full.tail())

,Transaction date,narration,transaction_type,amount,Category
20159,2023-08-24,indus pos rental jul23_5012669 (ref# m672810),DEBIT,413.0,utilites
20160,2023-12-22,indus pos rental nov23_5012669 (ref# m2191953),DEBIT,413.0,utilites
20161,2023-11-18,cash deposit by - atul singh - rathyatra crossing,CREDIT,140900.0,cash deposit
20162,2023-11-20,chq dep - micr clg - jaipur wbo: bhagwat i tex...,CREDIT,146895.0,cheque inward
20163,2024-01-16,chq dep - micr 1 clg - chandausi: shah c loth ...,CREDIT,25000.0,cheque inward

In [5]:
df_full.drop_duplicates(inplace=True)
df_full.reset_index(drop=True, inplace=True)
display(df_full.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19455 entries, 0 to 19454
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction date  19455 non-null  datetime64[ns]
 1   narration         19455 non-null  object
 2   transaction_type  19455 non-null  object
 3   amount            19455 non-null  float64
 4   Category          19455 non-null  object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 760.1+ KB

None

In [6]:
df_full['Category'].value_counts()

Category
cheque inward                 6319
bank charges                  2274
cash deposit                  2096
loan/emi payment              1967
cheque outward                1622
cash withdrawal               1497
credit card bill payment       624
utilites                       430
fuel                           393
loan received                  372
employee expenses / salary     271
logistics                      260
travel                         220
returns                        188
credit reversal                153
outward payment bounce         150
tax                            135
insurance payment              114
inward payment bounce          105
debit reversal                 100
government payouts              56
sip                             47
investment income               42
insurance claim                  9
government subsidy               6
bulk investment                  5
Name: count, dtype: int64

# Pincode & Locations

In [7]:
import pandas as pd

df1 = pd.read_csv('/content/drive/MyDrive/live_project/pincode.csv')
display(df1.head())
print(df1.info())

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
0,Telangana Circle,Hyderabad Region,Adilabad Division,Kothimir B.O,504273,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3638689,79.5376658
1,Telangana Circle,Hyderabad Region,Adilabad Division,Papanpet B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.4764899,79.5839230
2,Telangana Circle,Hyderabad Region,Adilabad Division,Kukuda B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,NaN,NaN
3,Telangana Circle,Hyderabad Region,Adilabad Division,Bareguda B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3285752,79.4760132
4,Telangana Circle,Hyderabad Region,Adilabad Division,Mosam B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3778044,79.6165209

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165627 entries, 0 to 165626
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   circlename    165627 non-null  object
 1   regionname    165312 non-null  object
 2   divisionname  165627 non-null  object
 3   officename    165627 non-null  object
 4   pincode       165627 non-null  int64
 5   officetype    165627 non-null  object
 6   delivery      165627 non-null  object
 7   district      164912 non-null  object
 8   statename     164912 non-null  object
 9   latitude      153620 non-null  object
 10  longitude     153625 non-null  object
dtypes: int64(1), object(10)
memory usage: 13.9+ MB
None

In [8]:
df_location = df1[['officename','pincode','officetype']].copy()
df_location.info()
df_location.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165627 entries, 0 to 165626
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   officename  165627 non-null  object
 1   pincode     165627 non-null  int64
 2   officetype  165627 non-null  object
dtypes: int64(1), object(2)
memory usage: 3.8+ MB

     officename  pincode officetype
0  Kothimir B.O   504273         BO
1  Papanpet B.O   504299         BO
2    Kukuda B.O   504299         BO
3  Bareguda B.O   504296         BO
4     Mosam B.O   504296         BO

In [9]:
df_location['officename'] = df_location['officename'].astype(str)
df_location['officename'] = df_location['officename'].str.replace(' B.O', '', regex=False)
df_location['officename'] = df_location['officename'].str.replace(' P.O', '', regex=False)
df_location['officename'] = df_location['officename'].str.replace(' H.O', '', regex=False)
df_location.head()

  officename  pincode officetype
0   Kothimir   504273         BO
1   Papanpet   504299         BO
2     Kukuda   504299         BO
3   Bareguda   504296         BO
4      Mosam   504296         BO

In [10]:
df_location = df_location.drop(columns=['officetype'])
df_location.head()

  officename  pincode
0   Kothimir   504273
1   Papanpet   504299
2     Kukuda   504299
3   Bareguda   504296
4      Mosam   504296

In [11]:
df_location = df_location.rename(columns={'officename': 'locations'})
df_location.head()

  locations  pincode
0  Kothimir   504273
1  Papanpet   504299
2    Kukuda   504299
3  Bareguda   504296
4     Mosam   504296

# IFSC codes

We get bank names , IFSC code and rtgs code(the first 4 characters of an ifsc code).

In [12]:
df_i = pd.read_excel('/content/drive/MyDrive/live_project/ifsc.xlsx')
display(df_i.head())
print(df_i.info())

,BANK,IFSC,BRANCH,ADDRESS,CITY1,CITY2,STATE,STD CODE,PHONE
0,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065001,RTGS-HO,"ABHYUDAYA BUILDING, KAMAL NATH MARG,NEHRU NAGA...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,0.0,9.653261e+09
1,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065002,ABHYUDAYA NAGAR,"ABHYUDAYA EDUCATION SOCIETY, OPP. BLDG. NO. 18...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.470264e+07
2,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065003,BAIL BAZAR,"KMSPMS SCHOOL, WADIA ESTATE, BAIL BAZAR-KURLA(...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.503220e+07
3,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065004,BHANDUP,"CHETNA APARTMENTS, J.M.ROAD, BHANDUP, MUMBAI-4...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.596316e+07
4,ABHYUDAYA COOPERATIVE BANK LIMITED,ABHY0065005,DARUKHANA,"POTIA IND.ESTATE, REAY ROAD (E), DARUKHANA, MU...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.377816e+07

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89433 entries, 0 to 89432
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   BANK      89433 non-null  object
 1   IFSC      89433 non-null  object
 2   BRANCH    89432 non-null  object
 3   ADDRESS   89433 non-null  object
 4   CITY1     89433 non-null  object
 5   CITY2     89433 non-null  object
 6   STATE     89433 non-null  object
 7   STD CODE  68851 non-null  float64
 8   PHONE     79561 non-null  float64
dtypes: float64(2), object(7)
memory usage: 6.1+ MB
None

In [13]:
df_i['IFSC'] = df_i['IFSC'].str.lower()
display(df_i.head())

,BANK,IFSC,BRANCH,ADDRESS,CITY1,CITY2,STATE,STD CODE,PHONE
0,ABHYUDAYA COOPERATIVE BANK LIMITED,abhy0065001,RTGS-HO,"ABHYUDAYA BUILDING, KAMAL NATH MARG,NEHRU NAGA...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,0.0,9.653261e+09
1,ABHYUDAYA COOPERATIVE BANK LIMITED,abhy0065002,ABHYUDAYA NAGAR,"ABHYUDAYA EDUCATION SOCIETY, OPP. BLDG. NO. 18...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.470264e+07
2,ABHYUDAYA COOPERATIVE BANK LIMITED,abhy0065003,BAIL BAZAR,"KMSPMS SCHOOL, WADIA ESTATE, BAIL BAZAR-KURLA(...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.503220e+07
3,ABHYUDAYA COOPERATIVE BANK LIMITED,abhy0065004,BHANDUP,"CHETNA APARTMENTS, J.M.ROAD, BHANDUP, MUMBAI-4...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.596316e+07
4,ABHYUDAYA COOPERATIVE BANK LIMITED,abhy0065005,DARUKHANA,"POTIA IND.ESTATE, REAY ROAD (E), DARUKHANA, MU...",MUMBAI,GREATER MUMBAI,MAHARASHTRA,22.0,2.377816e+07

In [14]:
df_full['narration'] = df_full['narration'].str.lower()
df_full['narration'] = df_full['narration'].str.replace('[^a-zA-Z0-9\s]', '', regex=True)
display(df_full.head())

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_294/298268865.py:2: SyntaxWarning: invalid escape sequence '\s'
  df_full['narration'] = df_full['narration'].str.replace('[^a-zA-Z0-9\s]', '', regex=True)

,Transaction date,narration,transaction_type,amount,Category
0,2023-08-01,by clg 460187 052 bangalore,CREDIT,10000.0,credit reversal
1,2023-08-01,by clg 970506 002 bangalore,CREDIT,25000.0,cheque inward
2,2023-08-01,by clg 797429 015 bangalore,CREDIT,22264.0,cheque inward
3,2023-08-03,brnclgchq paid to branch parking state bank of,DEBIT,5000.0,cheque outward
4,2023-08-03,achdrtp ach magmafin1211189123utib00000000151,DEBIT,106562.0,loan/emi payment

In [15]:
df_full['narration'] = df_full['narration'].str.lower()
df_full['narration'] = df_full['narration'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
display(df_full.head())

,Transaction date,narration,transaction_type,amount,Category
0,2023-08-01,by clg 460187 052 bangalore,CREDIT,10000.0,credit reversal
1,2023-08-01,by clg 970506 002 bangalore,CREDIT,25000.0,cheque inward
2,2023-08-01,by clg 797429 015 bangalore,CREDIT,22264.0,cheque inward
3,2023-08-03,brnclgchq paid to branch parking state bank of,DEBIT,5000.0,cheque outward
4,2023-08-03,achdrtp ach magmafin1211189123utib00000000151,DEBIT,106562.0,loan/emi payment

In [16]:
import sys
!{sys.executable} -m pip uninstall -y fuzzywuzzy > /dev/null
!{sys.executable} -m pip install rapidfuzz > /dev/null
from rapidfuzz import fuzz, process
print("Rapidfuzz is installed and imported.")

WARNING: Skipping fuzzywuzzy as it is not installed.
Rapidfuzz is installed and imported.

In [17]:
narration_matching_results = []

# Get unique IFSC codes (already lowercased in df_i['IFSC'])
unique_ifsc_codes = df_i['IFSC'].unique()

# Get the narration column as a list (already preprocessed in df_full['narration'])
narration_list = df_full['narration'].tolist()

# Iterate through each narration
for idx, narration in enumerate(narration_list):
    # Find the best matching IFSC code in the unique_ifsc_codes list
    best_match = process.extractOne(narration, unique_ifsc_codes, scorer=fuzz.token_set_ratio)

    if best_match:
        matched_ifsc = best_match[0]
        similarity_score = best_match[1]
        narration_matching_results.append({
            'Original_Narration_Index': idx,
            'Original_Narration': narration,
            'Matched_IFSC': matched_ifsc,
            'Similarity_Score': similarity_score
        })

# Convert the results list to a pandas DataFrame
df_narration_matches = pd.DataFrame(narration_matching_results)

# Display the head of the new DataFrame
display(df_narration_matches.head())
print(f"Total narration matches found: {len(df_narration_matches)}")

,Original_Narration_Index,Original_Narration,Matched_IFSC,Similarity_Score
0,0,by clg 460187 052 bangalore,barb0bangal,36.842105
1,1,by clg 970506 002 bangalore,barb0bangal,36.842105
2,2,by clg 797429 015 bangalore,barb0bangal,36.842105
3,3,brnclgchq paid to branch parking state bank of,barb0cgofar,35.087719
4,4,achdrtp ach magmafin1211189123utib00000000151,citi0000001,39.285714

Total narration matches found: 19455

In [18]:
matching_results = []

# Get unique IFSC codes to avoid redundant processing
unique_ifsc_codes = df_i['IFSC'].unique()

# Get the narration column as a list for process.extractOne efficiency
narration_list = df_full['narration'].tolist()

# Iterate through each unique IFSC code
for ifsc_code in unique_ifsc_codes:
    # Find the best match in the narration column
    # scorer=fuzz.ratio is a common choice for general string similarity
    best_match = process.extractOne(ifsc_code, narration_list, scorer=fuzz.ratio)

    if best_match:
        matched_narration = best_match[0]
        similarity_score = best_match[1]
        matching_results.append({
            'Original_IFSC': ifsc_code,
            'Matched_Narration': matched_narration,
            'Similarity_Score': similarity_score
        })

# Convert the results list to a pandas DataFrame
df_matches = pd.DataFrame(matching_results)

# Display the head of the new DataFrame
display(df_matches.head())

KeyboardInterrupt:

In [ ]:
display(df_matches.head())

In [ ]:
df_high_similarity = df_narration_matches[df_narration_matches['Similarity_Score'] > 90].copy()
display(df_high_similarity.head())
print(f"Number of high similarity matches: {len(df_high_similarity)}")

In [ ]:
display(df_full.iloc[2047])

# RTGS code

In [19]:
df_rtgs = pd.read_excel('/content/drive/MyDrive/live_project/rtgs.xlsx')

In [22]:
df_rtgs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   S.No                          231 non-null    float64
 1   Code                          231 non-null    object
 2   Bank Name                     232 non-null    object
 3   No. of RTGS enabled branches  232 non-null    int64
dtypes: float64(1), int64(1), object(2)
memory usage: 7.4+ KB

In [21]:
rtgs = df_rtgs['Code'].to_list()
print(len(rtgs))
print(rtgs[:5])

232
['ABHY', 'AMCB', 'AMDN', 'AIRP', 'AKJB']

In [24]:
import re

# Create a regex pattern to match any of the RTGS codes
# Ensure all codes are converted to strings before calling .lower()
rtgs_pattern = '|'.join(re.escape(str(code).lower()) for code in rtgs)

# Count how many narrations contain any of the RTGS codes
rtgs_in_narration_count = df_full['narration'].str.contains(rtgs_pattern, na=False, regex=True).sum()

print(f"Number of rows in df_full['narration'] containing an RTGS code: {rtgs_in_narration_count}")

Number of rows in df_full['narration'] containing an RTGS code: 7040

In [25]:
df_rtgs_matches = df_full[df_full['narration'].str.contains(rtgs_pattern, na=False, regex=True)]
display(df_rtgs_matches.head())

,Transaction date,narration,transaction_type,amount,Category
4,2023-08-03,achdrtp ach magmafin1211189123utib00000000151,DEBIT,106562.0,loan/emi payment
26,2023-08-24,neftidfbh23236866993ugro capital limitedattnh,CREDIT,15433.0,loan received
32,2023-09-03,achdrtp ach poonawallafin1238912652utib000000,DEBIT,106562.0,loan/emi payment
41,2023-09-12,brnclgchq paid to ms enterprises icici banking,DEBIT,2625.0,cheque outward
49,2023-09-16,rtgsreturnutibr52023091600288493ac 03,CREDIT,255518.0,returns

In [28]:
def tag_matched_rtgs(narration, pattern):
    # Ensure narration is a string to avoid errors with non-string types
    if not isinstance(narration, str):
        return narration

    # Use re.sub to replace all occurrences of the pattern with a tagged version
    # The 'flags=re.IGNORECASE' is important since the pattern was made lowercase.
    tagged_narration = re.sub(f'({pattern})', r'<MATCHED_RTGS>\1</MATCHED_RTGS>', narration, flags=re.IGNORECASE)
    return tagged_narration

# Explicitly create a copy to avoid SettingWithCopyWarning
df_rtgs_matches = df_full[df_full['narration'].str.contains(rtgs_pattern, na=False, regex=True)].copy()
df_rtgs_matches['tagged_narration'] = df_rtgs_matches['narration'].apply(lambda x: tag_matched_rtgs(x, rtgs_pattern))
display(df_rtgs_matches[['narration', 'tagged_narration']].head())

,narration,tagged_narration
4,achdrtp ach magmafin1211189123utib00000000151,achdrtp ach magmafin1211189123<MATCHED_RTGS>ut...
26,neftidfbh23236866993ugro capital limitedattnh,neft<MATCHED_RTGS>idfb</MATCHED_RTGS>h23236866...
32,achdrtp ach poonawallafin1238912652utib000000,achdrtp ach poonawallafin1238912652<MATCHED_RT...
41,brnclgchq paid to ms enterprises icici banking,brnclgchq paid to ms enterprises <MATCHED_RTGS...
49,rtgsreturnutibr52023091600288493ac 03,rtgsreturn<MATCHED_RTGS>utib</MATCHED_RTGS>r52...